### ISSUE TITLE
Latest build missing String extension, causing build failures

### ISSUE THREAD

**Issue by garyhooper** [lostatseajoshua/SwiftExpression#19]
Release 3.0 breaks compatibility with prior releases, due to the removal of the extension to String.  Please re-store this extension to the build.

**Comment by lostatseajoshua** [comment]
I moved the String extensions into its own file and I forgot to update the Cocapod sources path in the podspec. I will update this and push a fix.

**Comment by lostatseajoshua** [comment]
This has been fixed! d2014c91dfc03628a52d7dd25a4312ca6c4e52b3
Please update to Cocoapods SwiftExpression v3.0

```
pod 'SwiftExpression', '~> 3.0'
```
