### ISSUE TITLE
please add initializer for SwiftExpression.Regex.Match

### ISSUE THREAD

**Issue by garyhooper** [lostatseajoshua/SwiftExpression#20]
Would like to have an initializer for SwiftExpression.Regex.Match with no arguments required, e.g. `match = SwiftExpression.Regex.Match()`, to contain empty matches.

**Comment by lostatseajoshua** [comment]
This has been added here: 74ff612ac06ba054f83bd23363bb27d6eeb23f3d.
It should be in the latest Cocoapods v3.0 release.
